apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-dev
  labels:
    name: backend-service-dev
spec:
  type: NodePort
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30003
  selector:
    app: backend-app-dev  # Correction ici