apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy-dev
  labels:
    app: mysqldbdev  # Correction ici
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldbdev
  template:
    metadata:
      labels:
        app: mysqldbdev
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: devops