apiVersion: v1
kind: Service
metadata:
  name: mysqldbdev
  labels:
    name: mysql-service-dev
spec:
  ports:
    - port: 3307
      targetPort: 3306
  selector:
    app: mysqldbdev  # Correction ici